export default [
  {
    id: 1,
    name: 'Find Rocks',
    type: 'raw',
    active: false,
    color: '#555555',
    produces: 'Rocks',
    producesId: 1,
    produceAmount: 1,
    actionTime: 1000,
    mcProficiency: 1,
    mcpTriggerAmount: 0,
    triggered: true,
    mcpDiscoverAmount: 0,
    discovered: true,
    visible: false
  },
  {
    id: 7,
    name: 'Collect Clay',
    type: 'raw',
    active: false,
    color: '#ac6100',
    produces: 'Clay',
    producesId: 7,
    produceAmount: 1,
    actionTime: 1500,
    mcProficiency: 2,
    mcpTriggerAmount: 10,
    triggered: false,
    mcpDiscoverAmount: 20,
    discovered: false,
    visible: false
  },
  {
    id: 3,
    name: 'Fish',
    type: 'raw',
    active: false,
    color: '#84b0f1',
    produces: 'Fish',
    producesId: 3,
    produceAmount: 1,
    actionTime: 2000,
    mcProficiency: 3,
    mcpTriggerAmount: 40,
    triggered: false,
    mcpDiscoverAmount: 60,
    discovered: false,
    visible: false
  },
  {
    id: 2,
    name: 'Chop Wood',
    type: 'raw',
    active: false,
    color: '#425f0b',
    produces: 'Trees',
    producesId: 2,
    produceAmount: 1,
    actionTime: 2500,
    mcProficiency: 4,
    mcpTriggerAmount: 90,
    triggered: false,
    mcpDiscoverAmount: 120,
    discovered: false,
    visible: false
  },
  {
    id: 8,
    name: 'Plant Grain',
    type: 'raw',
    active: false,
    color: 'tan',
    produces: 'Grain',
    producesId: 8,
    produceAmount: 1,
    actionTime: 3000,
    mcProficiency: 5,
    mcpTriggerAmount: 160,
    triggered: false,
    mcpDiscoverAmount: 200,
    discovered: false,
    visible: false
  },
  {
    id: 4,
    name: 'Polish Gems',
    type: 'refine',
    active: false,
    color: '#176662',
    produces: 'Gems',
    producesId: 4,
    produceAmount: 1,
    actionTime: 6000,
    mcProficiency: 100,
    mcpTriggerAmount: 30000,
    triggered: false,
    mcpDiscoverAmount: 30000,
    discovered: false,
    decrementId: 1,
    decrementAmount: 256,
    visible: false
  },
  {
    id: 9,
    name: 'Fire Bricks',
    type: 'refine',
    active: false,
    color: '#AA5555',
    produces: 'Bricks',
    producesId: 9,
    produceAmount: 1,
    actionTime: 7000,
    mcProficiency: 200,
    mcpTriggerAmount: 32000,
    triggered: false,
    mcpDiscoverAmount: 35000,
    discovered: false,
    decrementId: 7,
    decrementAmount: 128,
    visible: false
  },
  {
    id: 6,
    name: 'Cook Fish',
    type: 'refine',
    active: false,
    color: '#be6868',
    produces: 'Fish',
    producesId: 6,
    produceAmount: 1,
    actionTime: 8000,
    mcProficiency: 300,
    mcpTriggerAmount: 39000,
    triggered: false,
    mcpDiscoverAmount: 45000,
    discovered: false,
    decrementId: 3,
    decrementAmount: 64,
    visible: false
  },
  {
    id: 5,
    name: 'Mill Boards',
    type: 'refine',
    active: false,
    color: '#563812',
    produces: 'Boards',
    producesId: 5,
    produceAmount: 1,
    actionTime: 9000,
    mcProficiency: 400,
    mcpTriggerAmount: 51000,
    triggered: false,
    mcpDiscoverAmount: 60000,
    discovered: false,
    decrementId: 2,
    decrementAmount: 32,
    visible: false
  },
  {
    id: 10,
    name: 'Bake Bread',
    type: 'refine',
    active: false,
    color: '#91752b',
    produces: 'Bread',
    producesId: 10,
    produceAmount: 1,
    actionTime: 10000,
    mcProficiency: 500,
    mcpTriggerAmount: 68000,
    triggered: false,
    mcpDiscoverAmount: 80000,
    discovered: false,
    decrementId: 8,
    decrementAmount: 16,
    visible: false
  }
];
